version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      aws-sdk:
        patterns:
          - "aws-sdk-*"
      rubocop:
        patterns:
          - "rubocop*"

  - package-ecosystem: "gomod"
    directory: "/generate_images"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
