inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

# Layout/LineLength:
#   Max: 120

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ™

RSpec/FilePath:
  CustomTransform:
    CoinGecko: coingecko

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
