inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

# Layout/LineLength:
#   Max: 120

Style/Documentation:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    CoinGecko: coingecko
