require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ™

RSpec/FilePath:
  CustomTransform:
    CoinGecko: coingecko

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context

Metrics/MethodLength:
  CountAsOne:
    - hash
