require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ™

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context

Metrics/MethodLength:
  CountAsOne:
    - hash

# TODO: Remove later. Deptecated in favor of RSpec/SpecFilePathSuffix and RSpec/SpecFilePathFormat.
RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    CoinGecko: coingecko

RSpec/MultipleMemoizedHelpers:
  Enabled: false
