require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - ™

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context

Metrics/MethodLength:
  CountAsOne:
    - hash

RSpec/FilePath:
  CustomTransform:
    CoinGecko: coingecko

RSpec/MultipleMemoizedHelpers:
  Enabled: false
