version: '3.9'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,sqs,s3
  app:
    build: .
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=test
      - LOGS_BUCKET=logs-bucket
      - CACHE_BUCKET=cache-bucket
      - TELEGRAM_BOT_API_TOKEN=123:token
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
    - localstack
volumes:
  bundle:
