version = 0.1

[default.global.parameters]
stack_name = "CoinMarketWhat"
region = "eu-north-1"

[default.deploy.parameters]
s3_prefix = "CoinMarketWhat"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[default.logs.parameters]
name = "TelegramWebhooks"
tail = "true"
