AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CoinMarketWhat

Globals:
  Function:
    Timeout: 3

Resources:
  TelegramWebhooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram_webhooks/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Events:
        Webhooks:
          Type: HttpApi
          Properties:
            Path: /
            Method: get

Outputs:
  WebhooksApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  TelegramWebhooks:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  TelegramWebhooksIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
