AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CoinMarketWhat

Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: CoinMarketWhatDB
  TelegramWebhooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram_webhooks/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !Ref DynamoDBTable
      Events:
        Webhooks:
          Type: HttpApi
          Properties:
            Path: /
            Method: get

Outputs:
  WebhooksApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  TelegramWebhooks:
    Description: "Lambda Function ARN"
    Value: !GetAtt TelegramWebhooks.Arn
  TelegramWebhooksIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt TelegramWebhooksRole.Arn
