AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CoinMarketWhat

Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CoinMarketWhatDB
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        -
          AttributeName: resource_id
          AttributeType: S
        -
          AttributeName: resource_type
          AttributeType: S
      KeySchema:
        -
          AttributeName: resource_id
          KeyType: HASH
        -
          AttributeName: resource_type
          KeyType: RANGE
  LogsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CoinMarketWhatLogsQueue
  TelegramWebhooks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: telegram_webhooks/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !GetAtt DynamoDBTable.Arn
            - Effect: Allow
              Action:
                - sqs:*
              Resource:
                - !GetAtt LogsQueue.Arn
            - Effect: Allow
              Action:
                - 'ssm:GetParameter*'
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/bots/telegram/CoinMarketWhat'
      Events:
        Webhooks:
          Type: HttpApi
          Properties:
            Path: /
            Method: post

Outputs:
  WebhooksApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  TelegramWebhooks:
    Description: "Lambda Function ARN"
    Value: !GetAtt TelegramWebhooks.Arn
  TelegramWebhooksIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt TelegramWebhooksRole.Arn
