name: rspec
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,sns,sqs,s3
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Wait for localstack to start
        # TODO: Find a better way, like: https://github.com/localstack/localstack/issues/732#issuecomment-799088216
        run: sleep 5
      - name: rspec
        env:
          LOCALSTACK_ENDPOINT: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: test
          LOGS_BUCKET: logs-bucket
          CACHE_BUCKET: cache-bucket
        run: |
          bundle exec rspec
