name: rspec
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,sqs,s3,ssm
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Wait for localstack
        run: test "$(curl -s http://localhost:4566/health | jq '[.services[] == "running"] | all')" == "true"
      - name: rspec
        env:
          AWS_ENDPOINT: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: test
          LOGS_QUEUE: http://localhost:4566/000000000000/CoinMarketWhatLogsQueue
        run: |
          bundle exec rspec
